# ===========================
# === Main logic switches ===
# ===========================
run_steps:
  build_database: false # Build the database of Bekanntmachungen by scraping the BMBF website
  build_sft_dataset: false # Build the training database with relevant document chunks for each prompt in the training data
  split_train_test: false # Split the training and testing sets for supervised fine-tuning using HuggingFace
  compute_huggingface_inferences: false # Get inferences from a HuggingFace model given a labelled dataset
  build_structured_database: false # Build a structured database of text chunks from the Bekanntmachungen documents to train a graph RAG model
  add_topic_tags: true # Add topic tags to the structured database of text chunks
  build_graph_database: false # Build the database of entities and relationships leveraging the chunk database to build a graph RAG
  build_chromadb: false # Build a ChromaDB vector database from the structured database of text chunks
  check_database_quality: false # NOTE: not implemented yet
  create_ground_truth: false # NOTE: not implemented yet
  run_summarisation_agent: false # NOTE: not implemented yet
  compute_traditional_metrics: false # Compute the BLEU, ROUGE and BertScore evaluation metrics between content generated by an agent and ground truth
  plot_traditional_metrics: false # Plot box plots and violin plots of the traditional evaluation metrics
  run_llm_as_judge: false # Run LLM-as-a-judge evaluation
  compute_overall_llm_judge_scores: false # Compute overall LLM-as-a-judge scores using the criteria specific scores
  compute_spearman_correlations: false # Compute the Spearman's Rank Correlation Coefficient between LLM judge and human assigned scores 


# ===========================
# === Reusable variables ===
# ===========================
vars:
  agent_model: &agent_model 'gemini-2.5-flash'
  llm_judge: &llm_judge 'llama3-70b-8192'
  
# --- Configuration for each step ---
# TODO: complete with the other steps later on

# ==================================
# === Database Building Settings ===
# ==================================
build_database:
  bmbf_base_url: "https://www.bmbf.de" # Base URL of the BMBF website
  bmbf_search_url: "https://www.bmbf.de/SiteGlobals/Forms/Suche/Bekanntmachungsuche/Bekanntmachungsuche_Formular.html?resourceId=1051612&pageLocale=de&input_=917290&gtp=1051594_list%253D1&resultsPerPage=50" # URL of the page listing Bekanntmachungen
  url_file: './meta_data/bekanntmachung_links.txt' # File of all Bekanntmachung URLs to be processed
  output_dir: './data/' # Directory where the extracted text files will be saved
  min_delay_seconds: 1 # Minimum and maximum delay in seconds between requests not to overload the server
  max_delay_seconds: 1.5
  log_file: './meta_data/failed_content_urls.txt' # File where logs of failed URLs will be saved

build_sft_dataset:
  data_folder: 'evaluation\data' # Folder containing the original data files in text or pdf format
  ground_truth_filepath: 'evaluation\ground_truth' # Folder containing the associated ground truth files in json format
  prompts_filepath: 'prompts\agent_prompts.json' # Json file containing the prompts
  output_filepath: 'supervised_fine_tuning\dataset.json' # Path where to save the resulting json file
  embedding_model_name: 'models/embedding-001' # Name of the embedding model to be used
  chunk_size: 4000 # Size of the text chunks to be created from the document
  chunk_overlap: 200 # Overlap between the text chunks 
  top_k_retrieval: 4 # Number of top relevant chunks to retrieve for each query

split_train_test:
  database_path: 'supervised_fine_tuning\dataset.json' # Path to the json file containing the dataset as formatted by Langchain
  training_set_path: 'supervised_fine_tuning\train_dataset.csv' # Path where to save the training set in CSV format
  testing_set_path: 'supervised_fine_tuning\test_dataset.csv' # Path where to save the testing set in CSV format
  train_proportion: 0.7 # Proportion of the dataset to be used for training
  random_seed: 42 # Seed for the random split

build_structured_database:
  data_folder_path: 'data' # Path to the folder containing the text files to be processed
  chunk_size: 4000 # Size of the text chunks to be created from the document
  chunk_overlap: 150 # Overlap between the text chunks
  output_path: &structured_database_path 'graph_rag/structured_database.jsonl' # Path where to save the resulting jsonl file
  clean_text: true # Whether to apply text cleaning heuristics to each chunk
  add_tags: true # Whether to add html style tags to indicate relevant information such as emails, phone numbers, amounts, dates

add_topic_tags:
  database_path: *structured_database_path # Path to the jsonl file containing the structured database of chunks
  output_path: 'graph_rag/structured_database_with_topics.jsonl' # Path where to save the resulting jsonl file

build_graph_database:
  database_path: 'graph_rag/structured_database_truncated.jsonl' # Path to the jsonl file containing the structured database of chunks
  output_path: 'graph_rag/graph_database_truncated_v9.jsonl' # Path where to save the resulting jsonl file
  llm_name: 'gemini-2.5-flash' # Name of the LLM to be used for concept extraction
  prompt_filepath: 'prompts/graph_rag_entity_extraction.json' # Path to the json file containing the prompt
  temperature: 0.1 # Temperature parameter for the LLM

build_chromadb:
  database_path: 'graph_rag/structured_database.jsonl' # Path to the jsonl file containing the structured database of chunks
  chroma_db_path: 'chroma_db' # Path where to save the ChromaDB database
  embedding_model_path: 'sentence-transformers/paraphrase-multilingual-mpnet-base-v2' # Path to the embedding model to be used
  batch_size: 500 # Number of database entries to process in each batch


# =============================
# === HuggingFace Settings ===
# =============================
compute_huggingface_inferences:
  dataset_path: 'supervised_fine_tuning/test_dataset.csv' # Path to the CSV file containing the dataset to be used for inference
  model_name: 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF' # Name of the model to use for inference
  output_dir: 'supervised_fine_tuning/test_inference_base' # Path where to save the inferences in json format, one per file
  max_new_tokens: 1024 # Maximum number of tokens for the inference

# =================================
# === Agent Evaluation Settings ===
# =================================
evaluation_shared_paths:
  gt_path: &gt_path './evaluation/ground_truth' # Path to the folder containing the json files with the ground truth
  gen_path: &gen_path './evaluation/generated_outputs/{agent_model}' # Path to the folder containing the json files with the agent generated information
  traditional_metrics_csv_file: &traditional_metrics_csv_path './evaluation/metrics/{agent_model}/metrics.csv' # Path to the CSV file where to save the BLEU, ROUGE and BertScore evaluation metrics
  llm_scores_csv_filepath: &llm_scores_csv_filepath './evaluation/llm_as_judge/{agent_model}_judged_by_{llm_judge}.csv' # Path for LLM as judge scores

compute_traditional_metrics:
  gt_path: *gt_path
  gen_path: *gen_path
  output_filepath: *traditional_metrics_csv_path

plot_traditional_metrics:
  csv_filepath: *traditional_metrics_csv_path
  output_folder_path: './evaluation/plots/{agent_model}' # Path to the folder where boxplots and violin plots of the evaluation metrics should be saved

run_llm_as_judge:
  model: *llm_judge # Name of the LLM to be used as judge
  temperature: 0.1 # Temprature parameter of the LLM judge
  text_path:  './evaluation/data' # Path to the folder that contains the text files of the Bekanntmachungen to be evaluated
  gt_path: *gt_path
  gen_path: *gen_path
  csv_output_filepath: *llm_scores_csv_filepath

compute_overall_llm_judge_scores:
  judge_scores_csv_path: *llm_scores_csv_filepath
  scoring_weights:
    correctness: 0.35
    completness: 0.35
    clarity: 0.1
    conciseness: 0.1
    adherence: 0.1
  output_csv_path: './evaluation/llm_as_judge/{agent_model}_judged_by_{llm_judge}_overall_scores.csv'

compute_spearman_correlations:
  llm_judge_scores_csv_path: *llm_scores_csv_filepath
  human_scores_csv_path: './evaluation/llm_as_judge/{agent_model}_judged_by_human.csv'
  output_csv_path: './evaluation/llm_as_judge/{agent_model}_human_vs_{llm_judge}_spearman_correlations.csv'