from langchain.chains import RetrievalQA
from langchain.chat_models import init_chat_model
from langchain_community.document_loaders import PyPDFLoader, UnstructuredPDFLoader, TextLoader
from langchain_community.vectorstores import DocArrayInMemorySearch
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from google.api_core.exceptions import ResourceExhausted
from tenacity import retry, stop_after_attempt, wait_random_exponential, retry_if_exception_type
import json
import os
from dotenv import load_dotenv
from time import time
#import pytesseract
from pdb import set_trace as st


### Extract information from a document containing a grant call. API key is expected to be contained in a .env file.
# Input arguments:
# - [str] doc_path: path to the document (currently either PDF or text)
# - [str] output_path: path to the folder where the resulting json file will be saved. If left empty, the file is not saved.
# - [str] model_name: name of the LLM to be used for the information extraction
# - [float] temperature: temperature of the LLM (default is 0.1)
# - [int] max_tokens: maximum number of tokens to be generated by the LLM
# - [str] model_provider: provider of the LLM (default is 'google_genai')
# - [int] chunk_size: size of the text chunks to be created from the document
# - [int] chunk_overlap: overlap between the text chunks
# Output:
# - [dict] extracted_info: structured information extracted from the document
def extract_info_from_document(
        doc_path: str,
        prompts_filepath: str,
        output_path: str = '', 
        model_name: str = "gemini-2.5-flash",
        temperature: float = 0.1, 
        max_tokens: int = 4000,
        model_provider: str = 'google_genai',
        chunk_size: int = 4000, 
        chunk_overlap: int = 200) -> dict: # NOTE: chunk size and overlap have to be somewhat tuned depending on the document size and content
    """
    Information to be extracted:
    - Main theme and objectives of the call
    - Inclusion and exclusion criteria (e.g. de-minimis rule, whether industrial partners are required, whether research institutions are allowed, etc.)
    - Deadline of the submission
    - Maximum funding allowed
    - Maximum duration of the project allowed
    - Information about the procedure to follow for the submission
    - Contact person(s) information for further questions if required
    - Any other relevant information that could be useful for the grant application process
    """
    start = time()

    # Check if the generated output already exists. If yes, skip to processing.
    if len(output_path) > 0:
        # Create an appropriate file name by retrieving the original document name and chaging the extension to .json
        file_name = os.path.basename(doc_path)
        if '.pdf' in file_name:
            new_file_name = file_name.replace('.pdf','.json')
        else:
            new_file_name = file_name.replace('.txt','.json')
        if os.path.isfile(os.path.join(output_path,new_file_name)):
            print(f"Output file {new_file_name} already exists. Skipping processing for {doc_path}.")
            with open(os.path.join(output_path,new_file_name),'r',encoding='utf-8') as f:
                extracted_info = json.load(f)
            return extracted_info

    # Load the document containing the grant (PDF or text)
    if doc_path.endswith('.pdf'):
        print(f"Loading PDF document from {doc_path}...")
        loader = PyPDFLoader(doc_path) 
        # # NOTE: this is only required for the extraction from complex PDF documents for which PyPDFLoader would fail
        # os.environ["OCR_AGENT"] = "tesseract" # Set the OCR agent to use Tesseract for OCR processing
        # pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe' # Path to the Tesseract executable
        #loader = UnstructuredPDFLoader(doc_path) # TODO: fix a problem with the pytesseract library causing this to fail. 

    elif doc_path.endswith('.txt'):
        print(f"Loading text document from {doc_path}...")
        loader = TextLoader(doc_path, encoding='utf-8')

    else:
        raise ValueError("The provided path is neither a PDF or text document. Please provide a valid file path.")
    
    # documents = loader.load()
    # text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    #split_docs = text_splitter.split_documents(documents)

    # Initialise the LLM
    load_dotenv()
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if gemini_api_key is None:
        raise ValueError("GEMINI_API_KEY not found among the environment variables defined in .env")
    os.environ['GOOGLE_API_KEY'] = gemini_api_key
    llm = init_chat_model(model_name, temperature=temperature, max_tokens=max_tokens, model_provider=model_provider) 

    # # Detect language of the document and translate it into English if necessary
    # translation_query = ChatPromptTemplate.from_template(
    #     "If the document is not in English, translate it into English. Provide only the translation. If already in English, return it as is.\n\n{text}"
    #     )
    # translation_chain = LLMChain(llm=llm, prompt=translation_query, output_key="english_text", verbose=True)
    # translated_chunks = []
    # for chunk in split_docs:
    #     translation = translation_chain({"text": chunk.page_content})
    #     translated_chunks.append(translation["english_text"])

    # Information extraction
    embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001") # NOTE: other embeddings could be experimented with
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    documents = loader.load()
    split_docs = text_splitter.split_documents(documents)
    index = DocArrayInMemorySearch.from_documents(split_docs, embeddings)
    #index = VectorstoreIndexCreator(embedding=embeddings,vectorstore_cls=DocArrayInMemorySearch).from_loaders([loader])

    # Load the prompts from the provided json file
    with open(prompts_filepath,'r',encoding='utf-8') as f:
        queries = json.load(f)
    
    # Create a RetrievalQA chain to query the index
    qa_chain = RetrievalQA.from_chain_type(
        llm,
        retriever=index.as_retriever(),
        return_source_documents=False,
        verbose=True,
    )

    # Use tenacity to automatically retry on rate limit errors with exponential backoff
    @retry(
        wait=wait_random_exponential(min=1, max=60),
        stop=stop_after_attempt(6),
        retry=(retry_if_exception_type(ResourceExhausted) | retry_if_exception_type(Exception))
    )
    def invoke_with_retry(chain: RetrievalQA, query: str) -> dict:
        """Wrapper for chain.invoke to add retry logic."""
        print(f"Invoking chain for query: {query[:40]}...")
        return chain.invoke({"query": query})

    # Obtain the results for each query and build the final dictionary
    extracted_info = {
        key: invoke_with_retry(qa_chain, query)["result"] for key, query in queries.items()
    }

    # # DEBUG to retrieve the most relevant chunks retrieved given a specific query
    # retriever = index.vectorstore.as_retriever()
    # t = retriever.get_relevant_documents(deadline_query)
    # t1 = retriever.get_relevant_documents(contact_query)
    # st()

    # Save the result dictionary into a json file if enabled
    if len(output_path) > 0:
        if not os.path.exists(output_path):
            os.makedirs(output_path)
        with open(os.path.join(output_path,new_file_name),'w',encoding='utf-8') as f:
            json.dump(extracted_info,f,indent=4,ensure_ascii=False)
    
    end = time()
    print('Information extraction for document %s completed in %.2f seconds.' % (doc_path,end-start))

    return extracted_info



### Extract information from webpage
### TODO: implement once the information extraction agent from text is properly working
def extract_info_from_webpage(webpage_url):
    """
    Steps to be performed:
    - Load webpage content
    - Detect language of the content
    - Translate into English if necessary
    - Split the text into chunks
    - Extract the required information from the chunks
    - Save and return the extracted information in a structured format

    Information to be extracted:
    - Main theme and objectives of the call
    - Inclusion and exclusion criteria (e.g. de-minimis rule, whether industrial partners are required, whether research institutions are allowed, etc.)
    - Deadline of the submission
    - Maximum funding allowed
    - Maximum duration of the project allowed
    - Information about the procedure to follow for the submission
    - Contact person(s) information for further questions if required
    - Any other relevant information that could be useful for the grant application process
    """
    pass  # Implementation goes here




### Main function
if __name__ == "__main__":

    # Hyper-parameters
    model_name = "gemini-2.5-flash" # NOTE: this can be changed to any other model name supported by the Google Generative AI API
    data_folder = r'C:\Users\Frederic\Documents\Programming\Grant-agent\evaluation\data'
    prompts_filepath = r'C:\Users\Frederic\Documents\Programming\Grant-agent\prompts\agent_prompts.json'
    output_path = r'C:\Users\Frederic\Documents\Programming\Grant-agent\evaluation\generated_outputs\\'+ model_name 
    # data_folder = r'C:\Users\Frederic\Documents\Programming\Grant-agent\evaluation\prompt_val_data' # NOTE: smaller sample of 5 documents for prompt testing
    # output_path = r'C:\Users\Frederic\Documents\Programming\Grant-agent\evaluation\generated_outputs\\'+ model_name + '_prompt_val' # NOTE: smaller sample of 5 documents for prompt testing
    chunk_size = 4000
    chunk_overlap = 20
    temperature = 0.1
    max_tokens = 4000
    model_provider = 'google_genai'
    
    # Loop on the examples with associated ground truth
    doc_list = [e for e in os.listdir(data_folder) if e.endswith('txt')]
    for doc_name in doc_list:
        doc_path = os.path.join(data_folder,doc_name)
        extract_info_from_document(
            doc_path=doc_path,
            prompts_filepath=prompts_filepath,
            output_path=output_path,
            model_name=model_name,
            temperature=temperature,
            max_tokens=max_tokens,
            model_provider=model_provider,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap)