import sys, os; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from langchain_google_genai import ChatGoogleGenerativeAI
from google.api_core.exceptions import ResourceExhausted
from tenacity import retry, stop_after_attempt, wait_random_exponential, retry_if_exception_type
from sentence_transformers import SentenceTransformer
from utils import load_config_from_yaml
import numpy as np
import pickle
import json
import os
import sys
from dotenv import load_dotenv
from time import time
#import pytesseract
from pdb import set_trace as st


### Extract information from a document containing a grant call using vector-based RAG.
### The document is chunked, embedded and stored in an in-memory vector store.
### Each topic query is answered by retrieving the most relevant chunks and passing them to the LLM.
### Two model providers are supported, selected via the model_provider parameter:
###   - 'google_genai': Gemini model via the Google Generative AI API (requires GEMINI_API_KEY in .env)
###   - 'huggingface': local HuggingFace model, optionally with a LoRA adapter from AutoTrain
###                    (no API key required; runs on GPU if available, otherwise CPU)
# Input arguments:
# - [str] doc_path: path to the document (currently either PDF or text)
# - [str] output_path: path to the folder where the resulting json file will be saved. If left empty, the file is not saved.
# - [str] model_name: name of the LLM to be used for the information extraction
# - [float] temperature: temperature of the LLM (default is 0.1)
# - [int] max_tokens: maximum number of tokens to be generated by the LLM
# - [str] model_provider: provider of the LLM — 'google_genai' or 'huggingface' (default is 'google_genai')
# - [str] autotrain_base_model_name: base model HuggingFace ID used to load the AutoTrain LoRA adapter
#                                    (only required when model_provider is 'huggingface' and model_name is an adapter)
# - [str] embedding_model_name: sentence-transformers model for local embeddings
#                                (only used when model_provider is 'huggingface')
# - [int] chunk_size: size of the text chunks to be created from the document
# - [int] chunk_overlap: overlap between the text chunks
# Output:
# - [dict] extracted_info: structured information extracted from the document
def vector_rag_info_extraction(
        doc_path: str,
        prompts_filepath: str,
        output_path: str = '',
        model_name: str = 'gemini-2.5-flash',
        temperature: float = 0.1,
        max_tokens: int = 4000,
        model_provider: str = 'google_genai',
        autotrain_base_model_name: str = '',
        embedding_model_name: str = 'paraphrase-multilingual-mpnet-base-v2',
        chunk_size: int = 4000,
        chunk_overlap: int = 200) -> dict:
    """
    Information to be extracted:
    - Main theme and objectives of the call
    - Inclusion and exclusion criteria (e.g. de-minimis rule, whether industrial partners are required, whether research institutions are allowed, etc.)
    - Deadline of the submission
    - Maximum funding allowed
    - Maximum duration of the project allowed
    - Information about the procedure to follow for the submission
    - Contact person(s) information for further questions if required
    - Any other relevant information that could be useful for the grant application process
    """
    from langchain.chains import RetrievalQA
    from langchain_community.document_loaders import PyPDFLoader, UnstructuredPDFLoader, TextLoader
    from langchain_community.vectorstores import DocArrayInMemorySearch
    from langchain.text_splitter import RecursiveCharacterTextSplitter
    from langchain_google_genai import GoogleGenerativeAIEmbeddings

    start = time()

    # Check if the generated output already exists. If yes, skip to processing.
    if len(output_path) > 0:
        # Create an appropriate file name by retrieving the original document name and chaging the extension to .json
        file_name = os.path.basename(doc_path)
        if '.pdf' in file_name:
            new_file_name = file_name.replace('.pdf','.json')
        else:
            new_file_name = file_name.replace('.txt','.json')
        if os.path.isfile(os.path.join(output_path,new_file_name)):
            print(f"Output file {new_file_name} already exists. Skipping processing for {doc_path}.")
            with open(os.path.join(output_path,new_file_name),'r',encoding='utf-8') as f:
                extracted_info = json.load(f)
            return extracted_info

    # Load the document containing the grant (PDF or text)
    if doc_path.endswith('.pdf'):
        print(f"Loading PDF document from {doc_path}...")
        loader = PyPDFLoader(doc_path) 
        # # NOTE: this is only required for the extraction from complex PDF documents for which PyPDFLoader would fail
        # os.environ["OCR_AGENT"] = "tesseract" # Set the OCR agent to use Tesseract for OCR processing
        # pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe' # Path to the Tesseract executable
        #loader = UnstructuredPDFLoader(doc_path) # TODO: fix a problem with the pytesseract library causing this to fail. 

    elif doc_path.endswith('.txt'):
        print(f"Loading text document from {doc_path}...")
        loader = TextLoader(doc_path, encoding='utf-8')

    else:
        raise ValueError("The provided path is neither a PDF or text document. Please provide a valid file path.")
    
    # documents = loader.load()
    # text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    #split_docs = text_splitter.split_documents(documents)

    # Initialise the LLM and embeddings model based on the selected provider
    load_dotenv()
    if model_provider == 'google_genai':
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if gemini_api_key is None:
            raise ValueError("GEMINI_API_KEY not found among the environment variables defined in .env")
        llm = ChatGoogleGenerativeAI(model=model_name, temperature=temperature, max_tokens=max_tokens, google_api_key=gemini_api_key)
        embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001", google_api_key=gemini_api_key)

    elif model_provider == 'huggingface':
        import torch
        from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline as hf_pipeline
        from peft import PeftModel
        from langchain_community.llms import HuggingFacePipeline
        from langchain_community.embeddings import HuggingFaceEmbeddings

        if not autotrain_base_model_name:
            raise ValueError("autotrain_base_model_name must be provided when model_provider is 'huggingface'")

        print(f"  Loading base model '{autotrain_base_model_name}' ...")
        hf_dtype = torch.float16 if torch.cuda.is_available() else torch.float32
        base_model = AutoModelForCausalLM.from_pretrained(
            autotrain_base_model_name, torch_dtype=hf_dtype, device_map='auto')
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        print(f"  Applying LoRA adapter '{model_name}' ...")
        peft_model = PeftModel.from_pretrained(base_model, model_name)
        peft_model = peft_model.merge_and_unload()  # fold adapter weights for faster inference

        pipe = hf_pipeline(
            'text-generation', model=peft_model, tokenizer=tokenizer,
            max_new_tokens=max_tokens, temperature=float(temperature), do_sample=bool(temperature > 0))
        llm = HuggingFacePipeline(pipeline=pipe)
        embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name)

    else:
        raise ValueError(f"Unsupported model_provider '{model_provider}'. Choose 'google_genai' or 'huggingface'.")

    # Information extraction
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    documents = loader.load()
    split_docs = text_splitter.split_documents(documents)
    index = DocArrayInMemorySearch.from_documents(split_docs, embeddings)
    #index = VectorstoreIndexCreator(embedding=embeddings,vectorstore_cls=DocArrayInMemorySearch).from_loaders([loader])

    # Load the prompts from the provided json file
    with open(prompts_filepath,'r',encoding='utf-8') as f:
        queries = json.load(f)
    
    # Create a RetrievalQA chain to query the index
    qa_chain = RetrievalQA.from_chain_type(
        llm,
        retriever=index.as_retriever(),
        return_source_documents=False,
        verbose=True,
    )

    # Use tenacity to automatically retry on rate limit errors with exponential backoff
    @retry(
        wait=wait_random_exponential(min=1, max=60),
        stop=stop_after_attempt(6),
        retry=(retry_if_exception_type(ResourceExhausted) | retry_if_exception_type(Exception))
    )
    def invoke_with_retry(chain: RetrievalQA, query: str) -> dict:
        """Wrapper for chain.invoke to add retry logic."""
        print(f"Invoking chain for query: {query[:40]}...")
        return chain.invoke({"query": query})

    # Obtain the results for each query and build the final dictionary
    extracted_info = {
        key: invoke_with_retry(qa_chain, query)["result"] for key, query in queries.items()
    }

    # # DEBUG to retrieve the most relevant chunks retrieved given a specific query
    # retriever = index.vectorstore.as_retriever()
    # t = retriever.get_relevant_documents(deadline_query)
    # t1 = retriever.get_relevant_documents(contact_query)
    # st()

    # Save the result dictionary into a json file if enabled
    if len(output_path) > 0:
        if not os.path.exists(output_path):
            os.makedirs(output_path)
        with open(os.path.join(output_path,new_file_name),'w',encoding='utf-8') as f:
            json.dump(extracted_info,f,indent=4,ensure_ascii=False)
    
    end = time()
    print('Information extraction for document %s completed in %.2f seconds.' % (doc_path,end-start))

    return extracted_info



### Extract information from a document containing a grant call using Graph RAG.
### Uses a pre-built knowledge graph and community summaries to provide context to the LLM.
### Broad topics (objective, criteria, procedure, misc) are answered via semantic search over
### community summaries filtered to the target document. Specific topics (deadline, max_funding,
### max_duration, contact) are answered via direct predicate-based graph traversal, with a
### fallback to community search if no relevant edges are found.
### API key is expected to be contained in a .env file.
# Input arguments:
# - [str] doc_path: path to the document (used to derive the document_id)
# - [str] knowledge_graph_path: path to the pickled NetworkX knowledge graph
# - [str] structured_database_path: path to the structured database JSONL (for raw chunk text)
# - [str] community_summaries_path: path to the community summaries JSON
# - [str] prompts_filepath: path to the prompts JSON file
# - [str] output_path: folder where the resulting JSON file is saved (skipped if empty)
# - [str] model_name: Gemini model name
# - [float] temperature: LLM temperature
# - [int] max_tokens: maximum tokens to generate
# - [int] top_k_communities: number of top communities to retrieve for broad topics
# - [str] embedding_model_name: sentence-transformers model for community summary embeddings
# Output:
# - [dict] extracted_info: structured information extracted from the document
def graph_rag_info_extraction(
        doc_path: str,
        knowledge_graph_path: str,
        structured_database_path: str,
        community_summaries_path: str,
        prompts_filepath: str,
        output_path: str = '',
        model_name: str = 'gemini-2.5-flash',
        temperature: float = 0.1,
        max_tokens: int = 4000,
        top_k_communities: int = 3,
        embedding_model_name: str = 'paraphrase-multilingual-mpnet-base-v2') -> dict:

    start = time()

    # --- Check for existing output ---
    file_name = os.path.basename(doc_path).replace('.txt', '.json').replace('.pdf', '.json')
    if len(output_path) > 0:
        output_file = os.path.join(output_path, file_name)
        if os.path.isfile(output_file):
            print(f"Output file {file_name} already exists. Skipping.")
            with open(output_file, 'r', encoding='utf-8') as f:
                return json.load(f)

    # document_id is the filename without extension — matches the prefix of chunk_ids in the graph
    document_id = os.path.splitext(os.path.basename(doc_path))[0]
    print(f"\nGraph RAG info extraction for document: {document_id}")

    # --- Load resources ---
    print("  Loading graph, chunk database and community summaries ...")
    with open(knowledge_graph_path, 'rb') as f:
        G = pickle.load(f)

    with open(community_summaries_path, 'r', encoding='utf-8') as f:
        community_summaries = json.load(f)

    chunk_db = {}
    with open(structured_database_path, 'r', encoding='utf-8') as f:
        for line in f:
            chunk = json.loads(line)
            chunk_db[chunk['metadata']['id']] = chunk['text']

    with open(prompts_filepath, 'r', encoding='utf-8') as f:
        queries = json.load(f)

    # --- LLM ---
    load_dotenv()
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if gemini_api_key is None:
        raise ValueError("GEMINI_API_KEY not found in .env")
    llm = ChatGoogleGenerativeAI(model=model_name, temperature=temperature,
                                 max_tokens=max_tokens, google_api_key=gemini_api_key)

    # --- Identify document-relevant edges and communities ---
    # An edge is document-relevant if at least one of its chunk_ids originates from this document.
    # A community is document-relevant if any of its nodes is an endpoint of such an edge.
    doc_edge_data = []  # list of (u, v, edge_attrs, doc_chunk_ids)
    doc_community_ids = set()

    for u, v, data in G.edges(data=True):
        doc_chunk_ids = [cid for cid in data.get('chunk_ids', []) if cid.startswith(document_id)]
        if doc_chunk_ids:
            doc_edge_data.append((u, v, data, doc_chunk_ids))
            doc_community_ids.add(str(G.nodes[u].get('community_id', '')))
            doc_community_ids.add(str(G.nodes[v].get('community_id', '')))
    doc_community_ids.discard('')

    print(f"  Found {len(doc_community_ids)} relevant communities and {len(doc_edge_data)} relevant edges.")

    # --- Embed document community summaries for broad topic retrieval ---
    doc_summaries = {cid: community_summaries[cid] for cid in doc_community_ids if cid in community_summaries}
    embedder = SentenceTransformer(embedding_model_name)
    summary_ids = list(doc_summaries.keys())
    summary_embeddings = embedder.encode(
        [doc_summaries[cid] for cid in summary_ids],
        normalize_embeddings=True, show_progress_bar=False
    )  # shape: (N, D)

    # --- Retrieval helpers ---

    # For broad topics: find top-k communities by cosine similarity to the query, then
    # collect their community summary and the raw text of associated document chunks.
    def retrieve_broad_context(query: str) -> str:
        if not summary_ids:
            return ""
        query_emb = embedder.encode([query], normalize_embeddings=True)[0]
        scores = summary_embeddings @ query_emb
        top_indices = np.argsort(scores)[::-1][:top_k_communities]

        context_parts = []
        for idx in top_indices:
            cid = summary_ids[idx]
            context_parts.append(f"[Community summary]: {doc_summaries[cid]}")
            community_chunk_ids = {
                doc_cid
                for u, v, _, doc_cids in doc_edge_data
                if str(G.nodes[u].get('community_id', '')) == cid
                or str(G.nodes[v].get('community_id', '')) == cid
                for doc_cid in doc_cids
            }
            texts = [chunk_db[cid] for cid in community_chunk_ids if cid in chunk_db]
            if texts:
                context_parts.append("[Source text]:\n" + "\n---\n".join(texts[:5]))
        return "\n\n".join(context_parts)

    # For specific topics: find edges whose predicates contain the topic's keyword(s), then
    # surface the object entity values as graph-extracted hints alongside the raw source chunks.
    # Falls back to broad community search if no matching edges are found.
    SPECIFIC_PREDICATE_KEYWORDS = {
        'deadline':     ['DEADLINE'],
        'max_funding':  ['FUNDING', 'AMOUNT'],
        'max_duration': ['DURATION'],
        'contact':      ['CONTACT'],
    }

    def retrieve_specific_context(topic: str, query: str) -> str:
        keywords = SPECIFIC_PREDICATE_KEYWORDS.get(topic, [])
        graph_values, relevant_chunk_ids = [], set()

        for _, v, data, doc_cids in doc_edge_data:
            predicates = data.get('predicates', [])
            if any(kw in pred.upper() for pred in predicates for kw in keywords):
                graph_values.append(G.nodes[v].get('entity_value', ''))
                relevant_chunk_ids.update(doc_cids)

        if not graph_values:
            return retrieve_broad_context(query)

        context_parts = [f"[Graph-extracted values for '{topic}']: {'; '.join(set(graph_values))}"]
        texts = [chunk_db[cid] for cid in relevant_chunk_ids if cid in chunk_db]
        if texts:
            context_parts.append("[Source text]:\n" + "\n---\n".join(texts[:5]))
        return "\n\n".join(context_parts)

    # --- LLM extraction with retry ---
    BROAD_TOPICS = {'objective', 'inclusion_criteria', 'exclusion_criteria', 'procedure', 'misc'}

    @retry(
        wait=wait_random_exponential(min=1, max=60),
        stop=stop_after_attempt(6),
        retry=(retry_if_exception_type(ResourceExhausted) | retry_if_exception_type(Exception))
    )
    def extract_with_retry(context: str, query: str) -> str:
        prompt = f"[Context from knowledge graph]:\n{context}\n\n{query}"
        response = llm.invoke([('human', prompt)])
        return str(response.content).strip()

    extracted_info = {}
    for topic, query in queries.items():
        print(f"  Extracting: {topic} ...")
        context = retrieve_broad_context(query) if topic in BROAD_TOPICS else retrieve_specific_context(topic, query)
        extracted_info[topic] = extract_with_retry(context, query)

    # --- Save ---
    if len(output_path) > 0:
        if not os.path.exists(output_path):
            os.makedirs(output_path)
        with open(os.path.join(output_path, file_name), 'w', encoding='utf-8') as f:
            json.dump(extracted_info, f, indent=4, ensure_ascii=False)

    end = time()
    print(f"Graph RAG extraction for {document_id} completed in {end - start:.2f} seconds.")
    return extracted_info


### Extract information from webpage
### TODO: implement once the information extraction agent from text is properly working
def extract_info_from_webpage(webpage_url):
    """
    Steps to be performed:
    - Load webpage content
    - Detect language of the content
    - Translate into English if necessary
    - Split the text into chunks
    - Extract the required information from the chunks
    - Save and return the extracted information in a structured format

    Information to be extracted:
    - Main theme and objectives of the call
    - Inclusion and exclusion criteria (e.g. de-minimis rule, whether industrial partners are required, whether research institutions are allowed, etc.)
    - Deadline of the submission
    - Maximum funding allowed
    - Maximum duration of the project allowed
    - Information about the procedure to follow for the submission
    - Contact person(s) information for further questions if required
    - Any other relevant information that could be useful for the grant application process
    """
    pass  # Implementation goes here




### Main function
if __name__ == "__main__":

    try:
        config = load_config_from_yaml(r'./config.yaml')
    except Exception:
        print("ERROR: YAML config file './config.yaml' not found!")
        sys.exit(1)

    run_steps = config.get('run_steps', {})

    ### Run vector RAG information extraction
    if run_steps.get('run_vector_rag', False):
        print("\n--- Running vector RAG info extraction ---")
        p = config.get('vector_rag', {})
        data_folder = p.get('data_folder')
        doc_list = [e for e in os.listdir(data_folder) if e.endswith('.txt')]
        for doc_name in doc_list:
            vector_rag_info_extraction(
                doc_path=os.path.join(data_folder, doc_name),
                prompts_filepath=p.get('prompts_filepath'),
                output_path=p.get('output_path', ''),
                model_provider=p.get('model_provider', 'google_genai'),
                model_name=p.get('model_name', 'gemini-2.5-flash'),
                autotrain_base_model_name=p.get('autotrain_base_model_name', ''),
                embedding_model_name=p.get('embedding_model_name', 'paraphrase-multilingual-mpnet-base-v2'),
                temperature=p.get('temperature', 0.1),
                max_tokens=p.get('max_tokens', 4000),
                chunk_size=p.get('chunk_size', 4000),
                chunk_overlap=p.get('chunk_overlap', 20))

    ### Run graph RAG information extraction
    if run_steps.get('run_graph_rag', False):
        print("\n--- Running graph RAG info extraction ---")
        p = config.get('graph_rag', {})
        data_folder = p.get('data_folder')
        doc_list = [e for e in os.listdir(data_folder) if e.endswith('.txt')]
        for doc_name in doc_list:
            graph_rag_info_extraction(
                doc_path=os.path.join(data_folder, doc_name),
                knowledge_graph_path=p.get('knowledge_graph_path'),
                structured_database_path=p.get('structured_database_path'),
                community_summaries_path=p.get('community_summaries_path'),
                prompts_filepath=p.get('prompts_filepath'),
                output_path=p.get('output_path', ''),
                model_name=p.get('model_name', 'gemini-2.5-flash'),
                temperature=p.get('temperature', 0.1),
                max_tokens=p.get('max_tokens', 4000),
                top_k_communities=p.get('top_k_communities', 3),
                embedding_model_name=p.get('embedding_model_name', 'paraphrase-multilingual-mpnet-base-v2'))